### ISSUE TITLE
 Cannot read property '$form' of null ErrorsComponent

### ISSUE THREAD

**Issue by terencechow** [davidkpiano/react-redux-form#472]
Not sure why I'm getting this. I get the below error when I add an errors component.

Not sure if this is relevant, but I started my project using [this starterkit](https://github.com/davezuko/react-redux-starter-kit) so I don't have a `combineForm` used in my app. Instead I have a reducer with something to the effect of

 `loginForm: modelReducer('loginForm',{username:'',password:''}`

(I don't think that should be a problem though because I have everything else in my app working except the Errors Component). Any reason why I might be getting this error? My code is below the error.

I'm using rrf 1.0.10, webpack 2.1.0-beta.22 and react 15.0.0

```
errors-component.js:246 Uncaught (in promise) TypeError: Cannot read property '$form' of null
    at mapStateToProps (http://10.2.20.215:3000/main.js:28605:50)
    at Connect.configureFinalMapState (http://10.2.20.215:3000/main.js:30863:27)
    at Connect.computeStateProps (http://10.2.20.215:3000/main.js:30850:23)
    at Connect.updateStatePropsIfNeeded (http://10.2.20.215:3000/main.js:30912:35)
    at Connect.render (http://10.2.20.215:3000/main.js:31047:40)
    at http://10.2.20.215:3000/main.js:35479:21
    at measureLifeCyclePerf (http://10.2.20.215:3000/main.js:34760:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://10.2.20.215:3000/main.js:35478:27)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://10.2.20.215:3000/main.js:35505:34)
    at ReactCompositeComponentWrapper.performInitialMount (http://10.2.20.215:3000/main.js:35047:30)
```

Here is my code:

`

     <Form
      model='loginForm'
      onSubmit={(form) => props.login(form)}
      >

      <Control.text
        model='.username'
        validators={{
          required: (val) => val && val.length
        }} />

      <Errors
        model='loginForm.username'
        messages={{
          required: 'Please provide an email address.'
        }}
        />`

**Comment by erin-doyle** [comment]
I think you're going to need to use [combineForms](http://davidkpiano.github.io/react-redux-form/docs/api/combineForms.html) or [createForms](http://davidkpiano.github.io/react-redux-form/docs/api/createForms.html) otherwise I don't think it's actually creating the form reducer.

**Comment by davidkpiano** [comment]
Yes, if you're going to use `modelReducer` and `formReducer` directly, I recommend this pattern:

```js
createStore(combineReducers({
  login: modelReducer('login', initialState),
  loginForm: formReducer('login', initialState),
}, ...);
```

Let me know if this resolves your issue.
