### ISSUE TITLE
Can't reset form second time.

### ISSUE THREAD

**Issue by robinspark** [davidkpiano/react-redux-form#606]
```
index.js:152  action @ 15:44:21.326 rrf/reset 
index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/reset", model: "reactReduxForm.myForm"}
index.js:172  error TypeError: Cannot read property '$form' of null
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115839:15)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115839:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115839:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20
```

`reset-action-reducer.js:36 Uncaught TypeError: Cannot read property '$form' of null`

**Comment by robinspark** [comment]
Why would this error be thrown when resetting an existing form? Shouldn't the reset function check to see if myField exists before checking myField.$form   ?

**Comment by robinspark** [comment]
I tried debugging reset-action-reducer.js
```
      var resetFieldState = function resetFieldState(field) {
        console.log('-------- resetFieldState --------- field:', field);
        ...
      }

```

For the first reset() which succeeds, the last 4 field values are as follows:
```
  field: $form: Object
  field: {
    model: "reactReduxForm.myForm.address
    ...
  }
  field: $form: Object
  field: {
    errors: Object
    focus: false
    initialValue: Array[0]
    length: 0
    __proto__: Array[0]
    intents: Array[0]
    model: "reactReduxForm.myForm.crew"
    pending: false
    pristine: true
    retouched: false
    submitFailed: false
    submitted: false
    touched: false
    valid: true
    validated: false
    validating: false
    validity: Object
    value: Array[0]
  }

```
For the second reset() which fails, the last 4 field values are as follows:
```
  field: {
    errors: Object
    focus: false
    initialValue: 3
    intents: Array[0]
    model: "crew.1.jobs.0"
    pending: false
    pristine: false
    retouched: false
    submitFailed: false
    submitted: false
    touched: false
    valid: true
    validated: false
    validating: false
    validity: Object
    value: 3
    __proto__: Object
  }
  field: {
      errors: Object
      focus: false
      initialValue: 3
      intents: Array[0]
      model: "crew.1.jobs.0"
      pending: false
      pristine: false
      retouched: false
      submitFailed: false
      submitted: false
      touched: false
      valid: true
      validated: false
      validating: false
      validity: Object
      value: 3
    }
  field: {pristine: false}
  field: null   // this causes the error.

```

**Comment by robinspark** [comment]
BTW, the model: "crew.1.jobs.0" is invalid. Not sure why it gets set to that.

**Comment by robinspark** [comment]
I fixed the issue by calling the following just before reset():

`actions.change(`reactReduxForm.myForm.crew`, []);`

**Comment by davidkpiano** [comment]
Does `myForm.crew` exist upon initialization? Resetting resets the model and form to their initial state, so if they didn't exist at the beginning, they won't exist when reset.

**Comment by robinspark** [comment]
Yes, myForm.crew exists upon initialization. It contains the exact same value just before I call:
actions.reset('reactReduxForm.myForm');

Works the first time. But, not everytime. Sometimes it doesn't fail on the 1st or second call, but after the nth call.

Debugging: last 3 rrf actions before the error, and value of crew:

```
index.js:152  action @ rrf/reset 
index.js:152  action @ rrf/setErrors 
index.js:152  action @ rrf/batch 
index.js:152  action @ rrf/change 
index.js:152  action @ rrf/setValidity 
index.js:152  action @ rrf/setSubmitFailed 
index.js:152  action @ rrf/setFieldsValidity 
index.js:152  action @ rrf/focus 
index.js:152  action @ rrf/blur 

index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/batch", model: "reactReduxForm.rrfJobDetails.crewQuantity", actions: Array[2]}
index.js:168  action Object {type: "rrf/blur", model: "reactReduxForm.rrfJobDetails.crewQuantity"}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails", value: Object, silent: false, multi: false}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails.crew", value: Array[0], silent: false, multi: false}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails.crewQuantity", value: 0, silent: false, multi: false}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails.equipment", value: Array[0], silent: false, multi: false}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails.equipment", value: Array[1], silent: false, multi: false}
index.js:168  action Object {type: "rrf/change", model: "reactReduxForm.rrfJobDetails.teamLeaderId", value: "", silent: false, multi: false}
index.js:168  action Object {type: "rrf/focus", model: "reactReduxForm.rrfJobDetails.crewQuantity", value: undefined, silent: true}
index.js:168  action Object {type: "rrf/reset", model: "reactReduxForm.rrfJobDetails"}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.address", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.clientId", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.contactId", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.crew", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.crewQuantity", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.date", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.equipment[0].item", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.equipment[0].quantity", errors: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.jobStartTime", errors: Object}
index.js:168  action Object {type: "rrf/setFieldsValidity", model: "reactReduxForm.rrfJobDetails", fieldsValidity: Object, options: Object}
index.js:168  action Object {type: "rrf/setSubmitFailed", model: "reactReduxForm.rrfJobDetails", submitFailed: true}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.address", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.clientId", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.contactId", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.crew", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.crewQuantity", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.equipment[0].item", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.equipment[0].quantity", validity: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.jobStartTime", validity: Object}

--- Last 3 rrf actions before the error:

index.js:152  action @ 10:37:51.875 rrf/setErrors 
index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/setErrors", model: "reactReduxForm.rrfJobDetails.equipment[0].quantity", errors: Object}

index.js:152  action @ 10:37:58.665 rrf/setValidity 
index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.jobStartTime", validity: Object}

  VALUE OF CREW:
    "crew": [
      {
        "firstName": "Severus",
        "lastName": "Snape",
        "phoneNumber": "0499888777",
        "address": {
          "number": "404",
          "street": "Blank St",
          "suburb": "Nowhere Town",
          "postcode": "3999",
          "state": "VIC"
        },
        "email": "abc@123.com.au",
        "id": "1"
      },
      {
        "firstName": "Dobby",
        "lastName": "House-elf",
        "phoneNumber": "0412341234",
        "address": {
          "number": "3",
          "street": "Wizard St",
          "suburb": "Hogwarts",
          "postcode": "2005",
          "state": "NSW"
        },
        "email": "d.house.elf@123.com.au",
        "id": "7"
      }
    ]

index.js:152  action @ 10:37:58.681 rrf/setValidity 
index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/setValidity", model: "reactReduxForm.rrfJobDetails.crew", validity: Object}

edit-job-page.js:43 -------- resetForm ---------
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {number: Object, street: Object, suburb: Object, postcode: Object, state: Object…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {0: Object, 1: Object, $form: Object}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {firstName: Object, lastName: Object, phoneNumber: Object, address: Object, email: Object…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {number: Object, street: Object, suburb: Object, postcode: Object, state: Object…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {$form: Object}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {0: Object, 1: Object, $form: Object}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {id: Object, name: Object, $form: Object}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {id: Object, name: Object, $form: Object}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {0: Object, $form: Object, validated: Object, value: null}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
reset-action-reducer.js:36 -------- resetFieldState --------- field: Object {pristine: false}
reset-action-reducer.js:36 -------- resetFieldState --------- field: null
index.js:152  action @ 10:38:13.230 rrf/reset 
index.js:164  prev state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
index.js:168  action Object {type: "rrf/reset", model: "reactReduxForm.rrfJobDetails"}
index.js:172  error TypeError: Cannot read property '$form' of null
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:15)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20
index.js:176  next state Object {auth: Object, toasts: Object, fetch: Object, form: Object, reactReduxForm: Object}
reset-action-reducer.js:38 Uncaught TypeError: Cannot read property '$form' of null
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:15)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20
    at Array.forEach (native)
    at mapValues (http://localhost:8080/assets/bundle.client.js:11724:30)
    at resetFieldState (http://localhost:8080/assets/bundle.client.js:115834:54)
    at http://localhost:8080/assets/bundle.client.js:11725:20

```

**Comment by davidkpiano** [comment]
Would it be possible for you to share a link to the repo, or stick it on www.esnextb.in ? This is probably some sort of edge case.

**Comment by robinspark** [comment]
The problem isn't readily reproducible, so I'm not sure how to reduce it to it's simplest form.

One thing I'm doing that I'm not sure about is calling validate directly on the form model, instead of field models as specified in the docs.

Is the following legal?
`actions.validate('reactReduxForm.myForm');`

This triggers a setValidity call on every field in turn. Crew is the last field to be validated.
actions.setValidity('reactReduxForm.myForm.firstName')
actions.setValidity('reactReduxForm.myForm.lastName')
...

**Comment by robinspark** [comment]
I think I was going down the wrong path. Setting the crew array to blank before calling actions.reset seemed to fix the problem at first, but that was only because 

After working out a precise number of steps to reproduce the problem, it turns out, a workaround that works is to use actions.change instead of actions.reset:
```
// resetForm: () => actions.reset('reactReduxForm.myForm'),
resetForm: () => actions.change('reactReduxForm.myForm', initialFormState),
```

**Comment by robinspark** [comment]
If new form fields are dynamically added to the model, will actions.reset() work properly?

**Comment by davidkpiano** [comment]
> If new form fields are dynamically added to the model, will actions.reset() work properly?

Yes, they should. I'll add a unit test to verify that.

**Comment by kabbi** [comment]
There is definitely some problem with `actions.reset()` not resetting the form state properly. I have reset action on `componentDidMount`, and it doesn't clear deep dynamic objects. I'll try to reproduce this in simple example.

**Comment by kabbi** [comment]
Here is the minimal gist for esnextb.in I could reproduce it with: https://gist.github.com/kabbi/26409b7d818562ddce5c63996709d41f

**Comment by davidkpiano** [comment]
Thank you! I'll take a look at it now.
