### ISSUE TITLE
resetValidity() throwing type error

### ISSUE THREAD

**Issue by sniepoort** [davidkpiano/react-redux-form#668]
For no particular reason that I can see, resetValidity('model') is throwing a type error

`TypeError: Cannot read property 'valid' of null
    at Object.assoc (http://localhost:5000/assets/app.bundle.js:14692:12)
    at http://localhost:5000/assets/app.bundle.js:14819:15
    at Array.reduce (native)
    at singleAssign (http://localhost:5000/assets/app.bundle.js:14818:29)
    at Array.reduce (native)
    at Object.assign (http://localhost:5000/assets/app.bundle.js:14812:33)
    at updateSubField (http://localhost:5000/assets/app.bundle.js:18743:29)
    at http://localhost:5000/assets/app.bundle.js:18730:26
    at Array.forEach (native)
    at http://localhost:5000/assets/app.bundle.js:18726:30`

**Comment by davidkpiano** [comment]
Does that model exist?

**Comment by davidkpiano** [comment]
@sniepoort Please send me a reproducible code example so I can further diagnose.

**Comment by sniepoort** [comment]
@davidkpiano I kind of have two threads going now with the same issue. Could you merge them or something? 
#662 
As for the reproducible example, i will get to that. Just have to brush up on how to do it, since i haven't done it before

**Comment by davidkpiano** [comment]
Like mentioned in the previous thread, start here: http://codepen.io/davidkpiano/pen/2cbfd61bdcff474ca6e40e8ed2221ef9

**Comment by davidkpiano** [comment]
Can you try this with the latest version?

**Comment by davidkpiano** [comment]
Closing due to inactivity. Please let me know if you still see this in the latest version.
