### ISSUE TITLE
Error thrown when selecting Control.checkbox by pressing space on keyboard

### ISSUE THREAD

**Issue by peralmq** [davidkpiano/react-redux-form#764]
### The Problem
An error is thrown when (de)selecting a checkbox with the keyboard 

### Steps to Reproduce
* Click in the rendered pane in the CodePen
* Tab to give focus to the checkbox
* Select the checkbox by pressing the spacebar

### Expected Behavior
The checkbox being selected without any error thrown

### Actual Behavior
The following error is thrown by rrf.
```
react.min.js:14 Uncaught TypeError: Cannot read property 'controlProps' of undefined
    at l (https://unpkg.com/react-redux-form@1.11.0/umd/ReactReduxForm.min.js:1:14983)
    at t.value (https://unpkg.com/react-redux-form@1.11.0/umd/ReactReduxForm.min.js:2:3677)
    at Object.r (https://unpkg.com/react@15.3.0/dist/react.min.js:14:16045)
    at i (https://unpkg.com/react@15.3.0/dist/react.min.js:12:22688)
    at Object.s [as executeDispatchesInOrder] (https://unpkg.com/react@15.3.0/dist/react.min.js:12:22903)
    at p (https://unpkg.com/react@15.3.0/dist/react.min.js:12:19281)
    at f (https://unpkg.com/react@15.3.0/dist/react.min.js:12:19407)
    at Array.forEach (native)
    at r (https://unpkg.com/react@15.3.0/dist/react.min.js:16:4324)
    at Object.processEventQueue (https://unpkg.com/react@15.3.0/dist/react.min.js:12:20414)
```

### Reproducible Code Example
http://codepen.io/anon/pen/VbPqNd?editors=0010

**Comment by mikkelwf** [comment]
Any update on this..?

**Comment by davidkpiano** [comment]
@mikkelwf I'm unable to reproduce the original issue:

![aug-16-2017 15-43-42](https://user-images.githubusercontent.com/1093738/29382183-d300a22a-8299-11e7-88d9-917a4aa9a282.gif)
